<?php

namespace HLIN601\MOOCBundle\Repository;

/**
 * StreamingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamingRepository extends \Doctrine\ORM\EntityRepository
{
}
