# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#  hlin601.form.registration:
#        class: HLIN601\UserBundle\Form\RegistrationType
#        tags:
#            - { name: form.type, alias: hlin601_user_registration }
  hlin601.form.profile_edit:
        class: HLIN601\UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: hlin601_user_profile_edit }
  hlin601.form.change_password:
        class: HLIN601\UserBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: hlin601_user_change_password }
            
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
